
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.asisoft.caen.host.service;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.2
 * 2011-07-04T17:53:59.805+02:00
 * Generated source version: 2.3.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "CaenRFIDProxyService",
                      portName = "CaenRFIDProxyPort",
                      targetNamespace = "http://service.host.caen.asisoft.com/",
                      wsdlLocation = "http://localhost:8888/caenrfid-proxy?wsdl",
                      endpointInterface = "com.asisoft.caen.host.service.CaenRFIDProxy")
                      
public class CaenRFIDProxyImpl implements CaenRFIDProxy {

    private static final Logger LOG = Logger.getLogger(CaenRFIDProxyImpl.class.getName());

    /* (non-Javadoc)
     * @see com.asisoft.caen.host.service.CaenRFIDProxy#getVersion(*
     */
    public java.lang.String getVersion() { 
        LOG.info("Executing operation getVersion");
        try {
            java.lang.String _return = "_return306381460";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.asisoft.caen.host.service.CaenRFIDProxy#getInventory(*
     */
    public net.java.dev.jaxb.array.StringArray getInventory() { 
        LOG.info("Executing operation getInventory");
        try {
            net.java.dev.jaxb.array.StringArray _return = new net.java.dev.jaxb.array.StringArray();
            java.util.List<java.lang.String> _returnItem = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnItemVal1 = "_returnItemVal1770481064";
            _returnItem.add(_returnItemVal1);
            _return.getItem().addAll(_returnItem);
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
