package com.asisoft.caen.host.service;

import java.net.URL;
import java.util.List;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;

import net.java.dev.jaxb.array.StringArray;

/**
 * This class was generated by Apache CXF 2.3.2 2011-07-04T17:53:59.670+02:00
 * Generated source version: 2.3.2
 * 
 */
public final class CaenRFIDProxyClient {

	private static final QName SERVICE_NAME = new QName("http://service.host.caen.asisoft.com/", "CaenRFIDProxyService");

	/**
     * 
     */
	private CaenRFIDProxy port;

	/**
     * 
     */
	public CaenRFIDProxyClient(String endpoint) {

		URL wsdlURL = CaenRFIDProxyService.WSDL_LOCATION;
		wsdlURL = getClass().getResource("/props/CaenProxyService.wsdl");

		CaenRFIDProxyService ss = new CaenRFIDProxyService(wsdlURL, SERVICE_NAME);
		port = ss.getCaenRFIDProxyPort();

		/*
		 * Setting the endpoint address for the web service
		 */
		BindingProvider bp = (BindingProvider) port;
		bp.getRequestContext().put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY, endpoint);
	}

	/**
	 * Returns the proxy port reference that allows to invoke the remote methods
	 * 
	 * @return
	 */
	public CaenRFIDProxy getClientPort() {
		return port;
	}

	/*
	 * Main - testing method
	 */
	public static void main(String args[]) throws Exception {

		CaenRFIDProxyClient client = new CaenRFIDProxyClient("http://localhost:8888/caenrfid-proxy");

		CaenRFIDProxy port = client.getClientPort();

		/*
		 * Testing each one of the methods
		 */

		{
			System.out.println("Invoking getVersion...");
			String version = port.getVersion();
			System.out.println("getVersion.result=" + version);

		}

		{
			System.out.println("Invoking getInventory...");
			StringArray inventory = port.getInventory();

			List<String> list = inventory.getItem();

			for (String tagid : list) {
				System.out.println(tagid);
			}
		}

		System.exit(0);
	}

}
