
/*
 * 
 */

package com.asisoft.caen.host.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.2
 * 2011-07-04T17:53:59.846+02:00
 * Generated source version: 2.3.2
 * 
 */


@WebServiceClient(name = "CaenRFIDProxyService", 
                  wsdlLocation = "http://localhost:8888/caenrfid-proxy?wsdl",
                  targetNamespace = "http://service.host.caen.asisoft.com/") 
public class CaenRFIDProxyService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.host.caen.asisoft.com/", "CaenRFIDProxyService");
    public final static QName CaenRFIDProxyPort = new QName("http://service.host.caen.asisoft.com/", "CaenRFIDProxyPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/caenrfid-proxy?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8888/caenrfid-proxy?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CaenRFIDProxyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CaenRFIDProxyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaenRFIDProxyService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns CaenRFIDProxy
     */
    @WebEndpoint(name = "CaenRFIDProxyPort")
    public CaenRFIDProxy getCaenRFIDProxyPort() {
        return super.getPort(CaenRFIDProxyPort, CaenRFIDProxy.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaenRFIDProxy
     */
    @WebEndpoint(name = "CaenRFIDProxyPort")
    public CaenRFIDProxy getCaenRFIDProxyPort(WebServiceFeature... features) {
        return super.getPort(CaenRFIDProxyPort, CaenRFIDProxy.class, features);
    }

}
