package com.asisoft.caen.host.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.3.2
 * 2011-07-04T17:53:59.837+02:00
 * Generated source version: 2.3.2
 * 
 */
 
@WebService(targetNamespace = "http://service.host.caen.asisoft.com/", name = "CaenRFIDProxy")
@XmlSeeAlso({net.java.dev.jaxb.array.ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface CaenRFIDProxy {

    @WebResult(name = "return", targetNamespace = "http://service.host.caen.asisoft.com/", partName = "return")
    @WebMethod
    public java.lang.String getVersion();

    @WebResult(name = "return", targetNamespace = "http://service.host.caen.asisoft.com/", partName = "return")
    @WebMethod
    public net.java.dev.jaxb.array.StringArray getInventory();
}
